updated main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,7 +30,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: markdoom-linux
-          path: ./dist/*.AppImage  # Adjust this path to the Linux output
+          path: dist/*.AppImage
 
   build-windows:
     runs-on: windows-latest
@@ -53,7 +53,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: markdoom-windows
-          path: ./dist/*.exe  # Adjust this path to the Windows output
+          path: dist/*.exe
 
   release:
     needs: [build-linux, build-windows]
@@ -66,22 +66,39 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: markdoom-linux
-          path: ./dist/linux
+          path: dist/linux
 
       - name: Download Windows Artifact
         uses: actions/download-artifact@v4
         with:
           name: markdoom-windows
-          path: ./dist/windows
+          path: dist/windows
+
+      - name: Display structure of downloaded files
+        run: ls -R
+        working-directory: dist
 
       - name: Create release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           tag: ${{ github.ref_name }}
         run: |
+          linux_file=$(find dist/linux -name "*.AppImage" -print -quit)
+          windows_file=$(find dist/windows -name "*.exe" -print -quit)
+          
+          if [ -z "$linux_file" ]; then
+            echo "Linux AppImage not found"
+            exit 1
+          fi
+          
+          if [ -z "$windows_file" ]; then
+            echo "Windows executable not found"
+            exit 1
+          fi
+          
           gh release create "$tag" \
               --repo="$GITHUB_REPOSITORY" \
               --title="${tag#v}" \
               --generate-notes \
-              ./dist/linux/*.AppImage#"markdoom-linux-${tag#v}.AppImage" \
-              ./dist/windows/*.exe#"markdoom-windows-${tag#v}.exe"
+              "$linux_file#markdoom-linux-${tag#v}.AppImage" \
+              "$windows_file#markdoom-windows-${tag#v}.exe"
